Make error upload job fail if it fails to fetch an error page

diff --git a/charts/govuk-rails-app/templates/static-error-page-upload-job.yaml b/charts/govuk-rails-app/templates/static-error-page-upload-job.yaml
--- a/charts/govuk-rails-app/templates/static-error-page-upload-job.yaml
+++ b/charts/govuk-rails-app/templates/static-error-page-upload-job.yaml
@@ -12,16 +12,18 @@ spec:
     spec:
       containers:
         - name: static-error-page-upload
+          # TODO: find a way to keep this up-to-date
           image: amazon/aws-cli:2.4.25
           command:
             - "/bin/sh"
             - "-c"
             - |
+              set -eu && \
               export ERROR_PAGES=(400 401 403 404 405 406 410 422 429 500 502 503 504) && \
               mkdir /error_pages && \
               for page in "${ERROR_PAGES[@]}"; do \
                 echo "${page}"
-                curl "http://static/templates/${page}.html.erb" > /error_pages/${page}.html; \
+                curl --fail "http://static/templates/${page}.html.erb" > /error_pages/${page}.html; \
               done; \
               aws s3 sync "/error_pages/" "s3://govuk-app-assets-{{ .Values.govukEnvironment }}/error_pages/"
       restartPolicy: Never
